[2025-08-12T16:23:02.496+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T16:23:02.564+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_hourly_pipeline.spark_hourly_change scheduled__2025-08-12T09:00:00+00:00 [queued]>
[2025-08-12T16:23:02.571+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_hourly_pipeline.spark_hourly_change scheduled__2025-08-12T09:00:00+00:00 [queued]>
[2025-08-12T16:23:02.571+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-08-12T16:23:02.582+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): spark_hourly_change> on 2025-08-12 09:00:00+00:00
[2025-08-12T16:23:02.589+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'crypto_hourly_pipeline', 'spark_hourly_change', 'scheduled__2025-08-12T09:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/crypto_pipeline.py', '--cfg-path', '/tmp/tmpm2931ruy']
[2025-08-12T16:23:02.593+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask spark_hourly_change
[2025-08-12T16:23:02.594+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=179) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-12T16:23:02.595+0000] {standard_task_runner.py:63} INFO - Started process 180 to run task
[2025-08-12T16:23:02.640+0000] {task_command.py:426} INFO - Running <TaskInstance: crypto_hourly_pipeline.spark_hourly_change scheduled__2025-08-12T09:00:00+00:00 [running]> on host 7d13ab6af910
[2025-08-12T16:23:02.728+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_hourly_pipeline' AIRFLOW_CTX_TASK_ID='spark_hourly_change' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-12T09:00:00+00:00'
[2025-08-12T16:23:02.728+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T16:23:02.782+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-12T16:23:02.783+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/project && python spark_hourly_change.py']
[2025-08-12T16:23:02.796+0000] {subprocess.py:86} INFO - Output:
[2025-08-12T16:23:04.727+0000] {subprocess.py:93} INFO - 2025-08-12 16:23:04,726 - INFO - Starting hourly change calculation...
[2025-08-12T16:23:04.775+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-17-openjdk-amd64/bin/java: No such file or directory
[2025-08-12T16:23:04.776+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2025-08-12T16:23:04.843+0000] {subprocess.py:93} INFO - 2025-08-12 16:23:04,843 - ERROR - Hourly change calculation failed: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-08-12T16:23:04.846+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-08-12T16:23:04.847+0000] {subprocess.py:93} INFO -   File "/opt/***/project/spark_hourly_change.py", line 176, in <module>
[2025-08-12T16:23:04.847+0000] {subprocess.py:93} INFO -     main()
[2025-08-12T16:23:04.848+0000] {subprocess.py:93} INFO -     ^^^^^^
[2025-08-12T16:23:04.848+0000] {subprocess.py:93} INFO -   File "/opt/***/project/spark_hourly_change.py", line 155, in main
[2025-08-12T16:23:04.848+0000] {subprocess.py:93} INFO -     spark = create_spark_session()
[2025-08-12T16:23:04.849+0000] {subprocess.py:93} INFO -             ^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T16:23:04.849+0000] {subprocess.py:93} INFO -   File "/opt/***/project/spark_hourly_change.py", line 48, in create_spark_session
[2025-08-12T16:23:04.849+0000] {subprocess.py:93} INFO -     .getOrCreate()
[2025-08-12T16:23:04.850+0000] {subprocess.py:93} INFO -      ^^^^^^^^^^^^^
[2025-08-12T16:23:04.850+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/sql/session.py", line 556, in getOrCreate
[2025-08-12T16:23:04.851+0000] {subprocess.py:93} INFO -     sc = SparkContext.getOrCreate(sparkConf)
[2025-08-12T16:23:04.852+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-12T16:23:04.852+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/core/context.py", line 523, in getOrCreate
[2025-08-12T16:23:04.852+0000] {subprocess.py:93} INFO -     SparkContext(conf=conf or SparkConf())
[2025-08-12T16:23:04.853+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/core/context.py", line 205, in __init__
[2025-08-12T16:23:04.853+0000] {subprocess.py:93} INFO -     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
[2025-08-12T16:23:04.853+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/core/context.py", line 444, in _ensure_initialized
[2025-08-12T16:23:04.853+0000] {subprocess.py:93} INFO -     SparkContext._gateway = gateway or launch_gateway(conf)
[2025-08-12T16:23:04.853+0000] {subprocess.py:93} INFO -                                        ^^^^^^^^^^^^^^^^^^^^
[2025-08-12T16:23:04.854+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/java_gateway.py", line 111, in launch_gateway
[2025-08-12T16:23:04.854+0000] {subprocess.py:93} INFO -     raise PySparkRuntimeError(
[2025-08-12T16:23:04.854+0000] {subprocess.py:93} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-08-12T16:23:05.048+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-08-12T16:23:05.056+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T16:23:05.087+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-08-12T16:23:05.098+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=crypto_hourly_pipeline, task_id=spark_hourly_change, run_id=scheduled__2025-08-12T09:00:00+00:00, execution_date=20250812T090000, start_date=20250812T162302, end_date=20250812T162305
[2025-08-12T16:23:05.121+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task spark_hourly_change (Bash command failed. The command returned a non-zero exit code 1.; 180)
[2025-08-12T16:23:05.139+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-12T16:23:05.163+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-12T16:23:05.164+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
